### ISSUE TITLE
Fails to build on 1.12.0-nightly (197be89f3 2016-08-15)

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#44]
```
error[E0063]: missing field `test_threads` in initializer of `test::TestOpts`
   --> src/compiletest.rs:126:5
    |
126 |     test::TestOpts {
    |     ^^^^^^^^^^^^^^
```

The field was added in https://github.com/rust-lang/rust/pull/35414.

**Comment by regexident** [comment]
Any chance to get this fix published on crates.io?

**Comment by dtolnay** [comment]
@regexident this was published as 0.2.1.

**Comment by regexident** [comment]
Uh, yeah.

Had run `cargo outdated` and `cargo add compiletest_rs` to update `compiletest_rs`.
Apparently `cargo add` doesn't detect `[dev-dependencies]` and just added a second entry to `[dependencies] `.

```toml
[dependencies]
compiletest_rs = "0.2.1"

[dev-dependencies]
compiletest_rs = "0.1.3"
```

Changing `Cargo.toml` to…

```toml
[dev-dependencies]
compiletest_rs = "0.2.1"
```
…fixed it of course. Sorry for bothering you.
