### ISSUE TITLE
Does not compile on rustc 1.19.0-nightly (f4209651e 2017-05-05)

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#64]
```
error[E0433]: failed to resolve. Could not find `Options` in `test`
   --> src/lib.rs:146:18
    |
146 |         options: test::Options::new(),
    |                  ^^^^^^^^^^^^^^^^^^ Could not find `Options` in `test`

error[E0560]: struct `test::TestOpts` has no field named `options`
   --> src/lib.rs:146:9
    |
146 |         options: test::Options::new(),
    |         ^^^^^^^^ `test::TestOpts` does not have this field

error: aborting due to previous error
```

**Comment by dtolnay** [comment]
Looks like this is caused by #63. I believe that commit should be reverted until rustup begins serving a nightly version that includes the break. [This dashboard](https://rusty-dash.com/nightlies) shows that the 2017-05-07 nightly is not out. @SimonSapin

**Comment by SimonSapin** [comment]
I have an obvious conflict of interest on what should be done with this crate/repo :)

But in the meantime you can downgrade with `cargo update -p compiletest_rs --precise 0.2.5`

**Comment by dtolnay** [comment]
I can downgrade but putting that command in the .travis.yml of every project that uses compiletest in CI, and then removing it when a new nightly is out, is not reasonable. I believe the change should be reverted until the new nightly is available and being served by rustup.

**Comment by SimonSapin** [comment]
Fair. I hadn’t thought of CI. It’s up to @laumann or @Manishearth to yank 0.2.6.

**Comment by laumann** [comment]
I can yank 0.2.6 and wait until nightly 2017-05-07 is out - I guess I can just undo the yank later?

**Comment by SimonSapin** [comment]
Yes, `cargo yank --undo` is a thing.

**Comment by dtolnay** [comment]
Thanks!

**Comment by oli-obk** [comment]
The nightly is out. Please unyank 0.2.6

**Comment by oli-obk** [comment]
Side note: maybe it would help to enable travis on this repository? There's a .travis.yml, but travis doesn't run.

**Comment by laumann** [comment]
@oli-obk: It's unyanked
