### ISSUE TITLE
Fails to build on rustc 1.26.0-nightly (0ff9872b2 2018-02-28)

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#103]
```
error[E0599]: no method named `rotate` found for type `&mut std::boxed::Box<[u8]>` in the current scope
    --> src/runtest.rs:2614:30
     |
2614 |                         tail.rotate(data.len());
     |                              ^^^^^^
```

I believe this was fixed in #102 but has not been released yet.

**Comment by laumann** [comment]
[0.3.7](https://crates.io/crates/compiletest_rs/0.3.7) is out
