### PR TITLE
Use stable libtest

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by mati865** [comment]
```
error: pretty-printing failed in round 0 revision None
status: exit code: 1
command: "rustc" "-" "-Z" "unpretty=expanded" "--target" "x86_64-unknown-linux-gnu" "-L" "/tmp/compiletestGdXCMX/macro.stage-id.pretty.aux" "-L" "target/debug" "-L" "target/debug/deps"
stdout:
------------------------------------------
------------------------------------------
stderr:
------------------------------------------
error: the option `Z` is only accepted on the nightly compiler
------------------------------------------
thread '[pretty] pretty/macro.rs' panicked at 'explicit panic', /home/travis/build/laumann/compiletest-rs/src/runtest.rs:2632:9
```

**Comment by Munksgaard** [comment]
Our [session-types library](https://github.com/Munksgaard/session-types) also broke due to the recent changes in compiletest. Your changes seem to fix some of the issue, but I'm still getting the following errors when trying to compile with this branch:

```
error[E0658]: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)                       
    --> /home/munksgaard/.cargo/git/checkouts/libtest-ed9c19a14a678411/584b2b3/src/lib.rs:1052:9                  
     |                                                                                                            
1052 |     all(target_vendor = "fortanix", target_env = "sgx")                                                    
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                         
                                                                                                                  
error[E0658]: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)                       
    --> /home/munksgaard/.cargo/git/checkouts/libtest-ed9c19a14a678411/584b2b3/src/lib.rs:1289:13                 
     |                                                                                                            
1289 |         all(target_vendor = "fortanix", target_env = "sgx")                                                
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^                                
```

That's on a stable build by the way.

**Comment by mati865** [comment]
@Munksgaard on which stable version?
`cfg_target_vendor` was stabilized in 1.33.0.

**Comment by Munksgaard** [comment]
@mati865, you're right, I was using an old stable version. After updating to 1.33.0 everything is dandy with `compiletest_rs = { git = "https://github.com/gnzlbg/compiletest-rs", branch = "stable_libtest" }` in my Cargo.toml.

File: .travis.yml [hunk 1]
```diff
@@ -2,13 +2,10 @@ language: rust
 matrix:
  include:
    - rust: nightly
-     env: FEATURES=""
+     env: FEATURES="--features unstable"
```
Comment (laumann) [inline .travis.yml]: How about `nightly` for the feature name?

File: src/lib.rs [hunk 2]
```diff
@@ -9,18 +9,15 @@
...
 #![deny(unused_imports)]
+#![cfg_attr(feature = "unstable", feature(rustc_private))]
 
-#[cfg(not(feature = "norustc"))]
+#[cfg(feature = "unstable")]
 extern crate rustc;
 
 #[cfg(unix)]
 extern crate libc;
-extern crate libtest as test;
```
Comment (laumann) [inline src/lib.rs]: Why the rename to `libtest`?

Comment (Manishearth) [reply src/lib.rs]: Don't want it to try and link with the local `test` crate that is unstable and broken now.

**Comment by Manishearth** [comment]
Is this ready to land? The PR description still says WIP.

**Comment by Manishearth** [comment]
Oh, the other PR needs to merge

**Comment by RalfJung** [comment]
Ping, any update on this?

File: src/lib.rs (hunk 2 above)
Comment (RalfJung) [reply src/lib.rs]: But an `as` import will never change what gets linked. So why not keep `extern crate libtest as test`?

**Comment by Manishearth** [comment]
We're currently reverting the libtest changes in Rust, but the path forward will likely involve landing this eventually, keeping it open for now.

**Comment by RalfJung** [comment]
What is the status of this? We just ran into another compiletest feature that hasn't been synced here yet (and it's been in rustc for more than 2 years).

**Comment by gnzlbg** [comment]
Someone needs to replace compiletest in rust-lang/rust with this crate to avoid the duplication. I don't think anybody is working on that.

**Comment by RalfJung** [comment]
Interesting, thanks! Some time ago I was told that someone is working on it and it would happen right after the next Rust release. Oh well.
