### PR TITLE
Fix nightly build failure (Added RunIgnored)

### LINKED ISSUE #129: Fails to compile: expected enum `test::RunIgnored`, found bool
As of the most recent nightly:

```console
error[E0308]: mismatched types                                                                                                 
   --> src/lib.rs:101:22                                                                                                       
    |                                                                                                                          
101 |         run_ignored: config.run_ignored,                                                                                 
    |                      ^^^^^^^^^^^^^^^^^^ expected enum `test::RunIgnored`, found bool                                     
    |                                                                                                                          
    = note: expected type `test::RunIgnored`                                                                                   
               found type `bool`
```

### PR DESCRIPTION
**Pull request by phansch**
The failure was caused by https://github.com/rust-lang/rust/pull/55053

Closes #129

### CODE REVIEW

**Comment by phansch** [comment]
I'm not sure about the failure on AppVeyor, it seems unrelated?

Also Travis CI doesn't seem to pick up the PR

File: src/common.rs [hunk 1]
```diff
@@ -143,7 +143,7 @@ pub struct Config {
     pub mode: Mode,
 
     /// Run ignored tests
-    pub run_ignored: bool,
+    pub run_ignored: RunIgnored,
```
Comment (laumann) [inline src/common.rs]: Is this the right way to fix it? [`common.rs`](https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/common.rs#L169) in rustc/compiletest has this field declared as a `bool`.
