### PR TITLE
Rustup to rustc 1.12.0-nightly (197be89f3 2016-08-15); fixes #44

### LINKED ISSUE #44: Fails to build on 1.12.0-nightly (197be89f3 2016-08-15)
```
error[E0063]: missing field `test_threads` in initializer of `test::TestOpts`
   --> src/compiletest.rs:126:5
    |
126 |     test::TestOpts {
    |     ^^^^^^^^^^^^^^
```

The field was added in https://github.com/rust-lang/rust/pull/35414.

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by Manishearth** [comment]
Merging immediately because there are other breakages to fix. Let me know if the fix was incomplete, cc @laumann
