### ISSUE TITLE
Fails to build on 1.25.0-nightly (7d6e5b9da 2018-01-27)

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#98]
```
error[E0560]: struct `test::TestOpts` has no field named `quiet`
  --> src/lib.rs:97:9
   |
97 |         quiet: config.quiet,
   |         ^^^^^^ `test::TestOpts` does not have this field
   |
   = note: available fields are: `list`, `filter`, `filter_exact`, `run_ignored`, `run_tests` ... and 8 others

warning: use of deprecated item 'std::slice::<impl [T]>::rotate': renamed to `rotate_left`
    --> src/runtest.rs:2614:30
     |
2614 |                         tail.rotate(data.len());
     |                              ^^^^^^
     |
     = note: #[warn(deprecated)] on by default
```

**Comment by laumann** [comment]
#99 is merged an [0.3.6](https://crates.io/crates/compiletest_rs/0.3.6) is out, which should fix this.
